

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA'


export const INICIARSESION_ERROR = 'INICIARSESION_ERROR'
export const INICIARSESION_EXITO = 'INICIARSESION_EXITO'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'

export const CERRAR_SESION = 'CERRAR_SESION'
